#!/usr/bin/env ruby

total = 0

copies = Hash.new { |h,k| h[k] = 1 }

ARGF.readlines.map(&:chomp).each do |card|
  md = card.match(/Card\s+(\d+): (.*?)\s+\|\s+(.*)$/)[1..3]

  idx = md[0].to_i
  win = md[1].split(/\s+/)
  our = md[2].split(/\s+/)

  puts "#{idx}: #{copies[idx]}"

  winners = (win & our).length
  (idx + 1 .. idx + winners).each { |i| copies[i] += copies[idx] }
end

puts copies.values.sum # 5920640
