#!/usr/bin/env ruby

lines = ARGF.readlines.map(&:chomp)

max_time = lines[0][/:(.*)/, 1].split(/\s+/).join.to_i
max_dist = lines[1][/:(.*)/, 1].split(/\s+/).join.to_i

winners = 0
(1 .. max_time).each do |hold|
  speed = 1 * hold
  distance = speed * (max_time - hold)

  winners += 1 if distance > max_dist
end

puts winners # 46561107
