#!/usr/bin/env ruby

steps = ARGF.readlines.map(&:chomp).join.split(',')

class Mash
  def self.char(current,char)
    current += char.ord
    current *= 17
    current = current % 256
  end

  def self.str(string)
    string.chars.inject(0) { |t,n| t = self.char(t,n) }
  end
end

puts steps.map { |s| Mash.str(s) }.sum # 506891
